### ISSUE TITLE
fatal error: error in backend: unable to translate instruction: call (in function: main)

### ISSUE THREAD

**Issue by beckadamtheinventor** [jacobly0/llvm-project#11]
ez80-clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 11.0.0 (https://github.com/jacobly0/llvm-project 12e4fac081cd4f76ba0a9b23fdf9bab5c1bf2155)

[main-0520a8.c.txt](https://github.com/jacobly0/llvm-project/files/4740664/main-0520a8.c.txt)
[main-0520a8.sh.txt](https://github.com/jacobly0/llvm-project/files/4740665/main-0520a8.sh.txt)

**Comment by jacobly0** [comment]
Yes, inline asm is not implemented yet.

**Comment by acagliano** [comment]
This is no inline asm in this program.
https://github.com/acagliano/titrek-calc

**Comment by jacobly0** [comment]
[This](https://github.com/acagliano/titrek-calc/blob/master/src/main.c#L100) is [this](https://github.com/CE-Programming/toolchain/blob/3ffaa8c2645ca07a1ef1aec78fa7698d644c394e/src/ce/intce.h#L26-L27).

**Comment by acagliano** [comment]
Ah. Didn't realize that. I'm still building with the zds toolchain, so... :p

**Comment by jacobly0** [comment]
I implemented inline asm at some point.
