### ISSUE TITLE
Extra Characters on Line

### ISSUE THREAD

**Issue by acagliano** [jacobly0/llvm-project#14]
When attempting to build TI-Trek with the latest version of the ez80-clang for OSX Big Sur, I get the following error:
```
/Users/acagliano/CEdev/include/fasmg-ez80/ld.alm [396] macro ? [208] read [4] sym temp [1] /Users/acagliano/CEdev/include/fasmg-ez80/../../lib/shared/assert.src [1]:
	section .text,'ax',@progbits
section [0]
Error: extra characters on line.
make: *** [bin/TITREK.bin] Error 2
```
I proceeded to re-install the older version I used to use, by renaming it from `ez80-clang-bck` to `ez80-clang` and made sure it was first in the path, and the program built as normal with no issues. Removed older version again, built again...error comes back. 
Let me know if you need more info than this error message.
Also the github for the project I was building is: https://github.com/acagliano/titrek-calc

**Comment by jacobly0** [comment]
The compiler and toolchain are updated together, so you can't update one without updating the other.

**Comment by acagliano** [comment]
Oh, because srldrvce/usbdrvce are behind master for the llvm toolchain. Forgot. 
Any updates on when those will be brought up to date with the master branch?
