### ISSUE TITLE
ez80 target not building by default

### ISSUE THREAD

**Issue by alexandre-lecoq** [jacobly0/llvm-project#16]
Hello,

I checked out the z80 branch and run the following commands :
PS C:\dev\llvmbuild> cmake ..\llvm-project\llvm\
PS C:\dev\llvmbuild> cmake --build .

It build a debug version of llvm but does not include the z80 target.
The llvm documentation indicated all targets are included by default.

My environment is windows 10 + VS 2019

**Comment by adriweb** [comment]
It's an experimental target. 

Take a look at the instructions here: https://github.com/jacobly0/llvm-project/wiki

**Comment by jacobly0** [comment]
Yep, specifically you need to configure cmake with `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=Z80`.

**Comment by alexandre-lecoq** [comment]
Thanks
