### ISSUE TITLE
Compiling for target Z80 produces a compiler with --version x86_64

### ISSUE THREAD

**Issue by gek169** [jacobly0/llvm-project#20]
Compiled for target z80 and got an x86_64 compiler.

**Comment by adriweb** [comment]
You probably didn't follow https://github.com/jacobly0/llvm-project/wiki#build-from-scratch correctly.

**Comment by gek169** [comment]
Yes I followed exactly that guide and executed those exact commands and got an x86_64 compiler.

**Comment by gek169** [comment]
Debian 10 Buster, GCC 8.3.0, Glibc 2.28-10 Debian

**Comment by adriweb** [comment]
What does it say when you call "ez80-clang --version" ? (With ez80-clang a symlink to the binary)

**Comment by gek169** [comment]
target linux-x86-64-gnu

**Comment by jacobly0** [comment]
Clang is a cross compiler that defaults to compiling to the native arch, you can use symlinks or command line arguments to change the target.

**Comment by gek169** [comment]
@jacobly0 I did that, and it didn't work

**Comment by jacobly0** [comment]
```
clang -target ez80 --version
clang version 13.0.0 (https://github.com/jacobly0/llvm-project 81fbcb46c7ebdac855b14e8f4e0422f028ff92ba)
Target: ez80
Thread model: posix
InstalledDir: /home/jacob/Programming/llvm/z80/build-Debug/bin
```

**Comment by gek169** [comment]
I'll have to rebuild to verify that

**Comment by gek169** [comment]
Maybe you shouldn't add labels before I tell you the results?

**Comment by gek169** [comment]
why are you deleting my posts?

**Comment by jacobly0** [comment]
This isn't a text thread, either wait until you have something relevant to say, or ask for help on IRC where frequent messages is more appropriate.

**Comment by gek169** [comment]
I was able to confirm that what you said is true and I got the compiler to report a z80 target and compile code for the TI84.
You can close the issue now.
