### ISSUE TITLE
VLAs are compiled incorrectly in both setup and teardown

### ISSUE THREAD

**Issue by mateoconlechuga** [jacobly0/llvm-project#28]
Minimal reproducible examples:

    int main(void)
    {
        int x = 0;
        for (int i = 0; i < 10; ++i) {
            int args[i];
            args[i-1] = i;
            x += args[0];
            args[0] = 0;
        }

        return x;
    }

---

    int main(void)
    {
        unsigned long x = 0;
        for (unsigned long i = 0; i < 10; ++i) {
            unsigned long args[i];
            for (unsigned long j = 0; j < i; ++j) {
                args[j] = i;
            }
            x += args[0];
            args[0] = 0;
        }
    
        return x;
    }

**Comment by jacobly0** [comment]
Closing because issue provides no metric by which to determine whether it is fixed.

**Comment by mateoconlechuga** [comment]
It's fixed when it actually compiles correctly.

**Comment by jacobly0** [comment]
Probably fixed by a213152dd72cfb05f40875047fca880d901b6dfb.
