### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by Lucretia** [jacobly0/llvm-project#34]
Hi,

I'd like to know if:

1. This is usable yet, and
2. What version of LLVM is this, is it still 9.0?

**Comment by adriweb** [comment]
1. Yes, and it's been used for several years for the [CE-Programming's toolchain](https://github.com/CE-Programming/toolchain) for instance. One issue you may encounter that's not solved yet is #12 though. 
2. it's based on v15. Rebases happen occasionally.

**Comment by Lucretia** [comment]
Ah, good stuff, thanks for answering.
